# Generated by Django 3.0.8 on 2020-07-03 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=2000)),
                ('Description', models.CharField(max_length=2000)),
                ('Score', models.FloatField()),
                ('StartDateValidation', models.DateTimeField(default=datetime.datetime(2020, 7, 3, 9, 20, 15, 989987))),
                ('EndDateValidation', models.DateTimeField(null=True)),
                ('Enabled', models.BooleanField(default=True)),
                ('Content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KindMission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2000)),
                ('DisplayName', models.CharField(max_length=2000)),
                ('Description', models.CharField(max_length=2000)),
                ('StartDateValidation', models.DateTimeField(default=datetime.datetime(2020, 7, 3, 9, 20, 15, 990345))),
                ('EndDateValidation', models.DateTimeField(null=True)),
                ('Score', models.FloatField()),
                ('KindActions', models.ManyToManyField(to='Hackathon_app.KindAction')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Missions',
            field=models.ManyToManyField(to='Hackathon_app.KindMission'),
        ),
    ]
