# Generated by Django 3.0.8 on 2020-07-03 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0002_auto_20200703_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindaction',
            name='StartDateValidation',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 9, 23, 35, 235334)),
        ),
        migrations.AlterField(
            model_name='kindmission',
            name='StartDateValidation',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 9, 23, 35, 235691)),
        ),
    ]
