# Generated by Django 3.0.8 on 2020-07-03 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0003_auto_20200703_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindaction',
            name='StartDateValidation',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 9, 39, 47, 168917)),
        ),
        migrations.AlterField(
            model_name='kindmission',
            name='StartDateValidation',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 9, 39, 47, 169259)),
        ),
    ]
