# Generated by Django 3.0.8 on 2020-07-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0004_auto_20200703_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindGenericDevice',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=2000, null=True)),
                ('SerialNo', models.CharField(max_length=2000)),
                ('ModelNo', models.CharField(max_length=2000)),
                ('Brand', models.CharField(max_length=2000)),
                ('Code', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='kindaction',
            name='StartDateValidation',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='kindmission',
            name='StartDateValidation',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.CreateModel(
            name='BinDevice',
            fields=[
                ('kindgenericdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Hackathon_app.KindGenericDevice')),
                ('LastUpdate', models.DateTimeField(auto_created=True)),
                ('MacAddress', models.CharField(max_length=2000)),
                ('LongitudePosition', models.FloatField(max_length=2000)),
                ('LatitudePosition', models.FloatField(max_length=2000)),
                ('Zone', models.CharField(max_length=2000)),
            ],
            bases=('Hackathon_app.kindgenericdevice',),
        ),
    ]
