# Generated by Django 3.0.8 on 2020-07-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0005_auto_20200703_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindIconFeature',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('DisplayName', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=2000)),
                ('Base64', models.BinaryField(max_length=9999)),
            ],
        ),
        migrations.AddField(
            model_name='bindevice',
            name='Icon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Hackathon_app.KindIconFeature'),
            preserve_default=False,
        ),
    ]
