# Generated by Django 3.0.8 on 2020-07-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0006_auto_20200703_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindaction',
            name='BinDevice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hackathon_app.BinDevice'),
        ),
    ]
