# Generated by Django 3.0.8 on 2020-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0007_kindaction_bindevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindiconfeature',
            name='Base64',
            field=models.CharField(max_length=9999),
        ),
    ]
