# Generated by Django 3.0.8 on 2020-07-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0008_auto_20200703_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindiconfeature',
            name='TypeImage',
            field=models.PositiveSmallIntegerField(choices=[('SVG', 'SVG'), ('PNG', 'PNG')], default=0),
            preserve_default=False,
        ),
    ]
