# Generated by Django 3.0.8 on 2020-07-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0010_auto_20200703_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindiconfeature',
            name='Scale',
            field=models.FloatField(default=1),
        ),
    ]
