# Generated by Django 3.0.8 on 2020-07-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0011_kindiconfeature_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindiconfeature',
            name='TypeImage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SVG'), (1, 'PNG')]),
        ),
    ]
