# Generated by Django 3.0.8 on 2020-07-03 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0013_kindaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kindaction',
            name='BinDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hackathon_app.BinDevice'),
        ),
    ]
