# Generated by Django 3.0.8 on 2020-07-04 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0014_auto_20200703_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=2000)),
                ('Name', models.CharField(max_length=2000)),
                ('Description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='kindaction',
            name='Report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hackathon_app.ReportMap'),
        ),
    ]
