# Generated by Django 3.0.8 on 2020-07-04 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0015_auto_20200704_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmap',
            name='Icon',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Hackathon_app.KindIconFeature'),
            preserve_default=False,
        ),
    ]
