# Generated by Django 3.0.8 on 2020-07-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0016_reportmap_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmap',
            name='Icon',
        ),
        migrations.AddField(
            model_name='reportmap',
            name='LatitudePosition',
            field=models.FloatField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportmap',
            name='LongitudePosition',
            field=models.FloatField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
