# Generated by Django 3.0.8 on 2020-07-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackathon_app', '0018_reportmap_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='Hackathon_app.Role'),
        ),
    ]
